# develop stage
FROM node:14 as develop-stage
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install -g @vue/cli
RUN npm install
COPY ./frontend .
EXPOSE 3000
# build stage
#FROM develop-stage as build-stage
#RUN npm build
# production stage
#FROM nginx:1.15.7-alpine as production-stage
#COPY --from=build-stage /app/dist /usr/share/nginx/html
#EXPOSE 80
#CMD ["nginx", "-g", "daemon off;"]