FROM node:16

ENV NODE_ENV development
# Add a work directory
WORKDIR /app
# Cache and Install dependencies
COPY frontend/package.json .
COPY frontend/package-lock.json .
RUN npm install
# Copy app files
COPY ./frontend .
# Expose port
EXPOSE 3000
# Start the app
CMD [ "npm", "start" ]