# Generated by Django 4.2.10 on 2024-02-26 00:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prio', models.PositiveSmallIntegerField(verbose_name='priority in renting queue')),
                ('name', models.CharField(max_length=100, verbose_name='name of the priority class')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='description of the priority class')),
            ],
        ),
    ]
