# Generated by Django 4.1.2 on 2022-10-26 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internalinfoobjecttype',
            old_name='objecttype',
            new_name='object_type',
        ),
        migrations.RenameField(
            model_name='publicinfoobjecttype',
            old_name='objecttype',
            new_name='object_type',
        ),
        migrations.AddField(
            model_name='rentaloperation',
            name='return_processor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_processor', to=settings.AUTH_USER_MODEL, verbose_name='person who processes the return'),
        ),
        migrations.AlterField(
            model_name='internalinfoobjecttype',
            name='type',
            field=models.CharField(max_length=20, verbose_name='Information type'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='authorized',
            field=models.BooleanField(default=False, verbose_name='authorized to rent objects'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='newsletter',
            field=models.BooleanField(default=False, verbose_name='newsletter signup'),
        ),
        migrations.AlterField(
            model_name='publicinfoobjecttype',
            name='type',
            field=models.CharField(max_length=20, verbose_name='material type'),
        ),
        migrations.AlterField(
            model_name='rentalobject',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
