# Generated by Django 4.1.2 on 2022-10-26 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_objecttype_internalinfoobjecttype_object_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalobjecttype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentalobjecttypes', to='base.category'),
        ),
    ]
