# Generated by Django 4.1.2 on 2022-11-02 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_rentalobjecttype_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('inventory_editing', 'able to edit and create the inventory and got nearly full access'), ('general_access', 'got general Access to everything, but no editing rights'), ('lending_access', 'is able to lend stuff')]},
        ),
    ]
