# Generated by Django 4.1.2 on 2022-11-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_profile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalobject',
            name='internal_identifier',
        ),
        migrations.AddField(
            model_name='rentalobjecttype',
            name='prefix_identifier',
            field=models.CharField(default='LZ', max_length=20),
        ),
    ]
