# Generated by Django 4.1.2 on 2022-11-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_rentalobject_internal_identifier_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rentalobjecttype',
            constraint=models.UniqueConstraint(fields=('prefix_identifier',), name='unique_id_prefix'),
        ),
    ]
