# Generated by Django 4.1.2 on 2022-11-02 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rentalobjecttype_unique_id_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalobject',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentalobjects', to='base.rentalobjecttype'),
        ),
    ]
