# Generated by Django 4.1.3 on 2022-11-18 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_alter_rentalobject_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejected', models.BooleanField()),
                ('operation_number', models.BigIntegerField()),
                ('picked_up_at', models.DateTimeField(default=None, null=True)),
                ('handed_out_at', models.DateTimeField(default=None, null=True)),
                ('received_back_at', models.DateTimeField(default=None, null=True)),
                ('lender', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lender', to=settings.AUTH_USER_MODEL)),
                ('objects', models.ManyToManyField(to='base.rentalobject')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter', to='base.profile')),
                ('return_processor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_processor', to=settings.AUTH_USER_MODEL, verbose_name='person who processes the return')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('reserved_from', models.DateTimeField()),
                ('reserved_until', models.DateTimeField()),
                ('operation_number', models.BigIntegerField()),
                ('count', models.PositiveSmallIntegerField()),
                ('objecttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.rentalobjecttype')),
                ('reserver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserver', to='base.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='RentalOperation',
        ),
        migrations.AddField(
            model_name='rentalobjecttype',
            name='tags',
            field=models.ManyToManyField(to='base.tag'),
        ),
    ]
