# Generated by Django 4.1.3 on 2022-11-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rental_reservation_tag_delete_rentaloperation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='operation_number',
        ),
    ]
