# Generated by Django 4.1.3 on 2022-11-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_reservation_operation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='operation_number',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
