# Generated by Django 4.1.3 on 2022-11-18 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_reservation_operation_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='objects',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='picked_up_at',
        ),
        migrations.AddField(
            model_name='rental',
            name='rentedobjects',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.rentalobject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='reservation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.reservation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_until',
            field=models.DateField(),
        ),
    ]
