# Generated by Django 4.1.3 on 2022-11-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_rental_objects_remove_rental_picked_up_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalobject',
            name='internal_identifier',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rental',
            name='received_back_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name='rentalobject',
            constraint=models.UniqueConstraint(fields=('type', 'internal_identifier'), name='unique_identifier'),
        ),
    ]
