# Generated by Django 4.1.3 on 2022-11-23 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rentalobject_internal_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prio',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='base.priority'),
        ),
    ]
