# Generated by Django 4.1.4 on 2022-12-27 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_profile_prio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectTypeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='material type')),
                ('public', models.BooleanField()),
                ('order', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='internalinfoobjecttype',
            name='object_type',
        ),
        migrations.RemoveField(
            model_name='publicinfoobjecttype',
            name='object_type',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='rejected',
            new_name='canceled',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prio',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='base.priority'),
        ),
        migrations.AlterField(
            model_name='rentalobjecttype',
            name='image',
            field=models.ImageField(default='nopicture.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='rentalobjecttype',
            name='tags',
            field=models.ManyToManyField(blank=True, to='base.tag'),
        ),
        migrations.AddConstraint(
            model_name='settings',
            constraint=models.UniqueConstraint(fields=('type',), name='unique_settings'),
        ),
        migrations.DeleteModel(
            name='InternalInfoObjectType',
        ),
        migrations.DeleteModel(
            name='PublicInfoObjectType',
        ),
        migrations.AddField(
            model_name='objecttypeinfo',
            name='object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.rentalobjecttype'),
        ),
    ]
