# Generated by Django 4.1.4 on 2022-12-28 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rentalobjecttype_manufacturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalobjecttype',
            old_name='description',
            new_name='shortdescription',
        ),
    ]
