# Generated by Django 4.1.4 on 2022-12-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_rename_description_rentalobjecttype_shortdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalobjecttype',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
