# Generated by Django 4.1.4 on 2023-01-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_text_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
