# Generated by Django 4.1.4 on 2023-01-06 19:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0025_remove_profile_authorized_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RentalObjectstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(default='defekt')),
                ('from_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('until_date', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999))),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.rentalobject', verbose_name='Rentalobjecttype')),
            ],
        ),
    ]
