# Generated by Django 4.1.4 on 2023-01-07 01:16

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_rename_type_rentalobjectstatus_rental_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalobjectstatus',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rentalobjectstatus',
            name='until_date',
            field=models.DateField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)),
        ),
    ]
