# Generated by Django 4.1.4 on 2023-01-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_rentalobjectstatus_rentable_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rentalobjectstatus',
            constraint=models.CheckConstraint(check=models.Q(('from_date__lte', models.F('until_date'))), name='enforce_from_date_lte_until_date'),
        ),
    ]
