# Generated by Django 4.1.4 on 2023-01-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_remove_rentalobjectstatus_enforce_from_date_lte_until_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='canceled',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
