# Generated by Django 4.1.4 on 2023-01-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_rental_canceled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='rentedobjects',
            new_name='rented_objects',
        ),
    ]
