# Generated by Django 4.1.4 on 2023-01-07 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_rename_rentedobjects_rental_rented_objects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='rented_objects',
            new_name='rented_object',
        ),
    ]
