# Generated by Django 4.1.4 on 2023-01-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_rename_rented_objects_rental_rented_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='public',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
