# Generated by Django 4.1.4 on 2023-01-10 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0035_settings_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('inventory_editing', 'able to edit and create the inventory and got nearly full access'), ('lending_access', 'is able to lend stuff')]},
        ),
        migrations.AlterField(
            model_name='profile',
            name='prio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.priority'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MaxRentDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('prio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.priority')),
                ('rental_object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.rentalobjecttype')),
            ],
        ),
    ]
