# Generated by Django 4.1.4 on 2023-01-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_profile_options_alter_profile_prio_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='maxrentduration',
            constraint=models.UniqueConstraint(fields=('prio', 'rental_object_type'), name='unique_prio_type'),
        ),
    ]
