# Generated by Django 4.1.4 on 2023-01-15 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_files_alter_profile_prio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='template',
            new_name='file',
        ),
    ]
