# Generated by Django 4.1.5 on 2023-01-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_remove_rental_renter_alter_profile_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='operation_number',
            new_name='rental_number',
        ),
    ]
