# Generated by Django 4.1.5 on 2023-01-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_rename_operation_number_rental_rental_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rental',
            name='rental_handed_out_lte_received_date',
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('handed_out_at__lte', models.F('received_back_at')), ('received_back_at__isnull', True), _connector='OR')), name='rental_handed_out_lte_received_date'),
        ),
    ]
