# Generated by Django 4.1.5 on 2023-01-19 01:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_remove_rental_rental_handed_out_lte_received_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='reserved_until',
            field=models.DateField(default=datetime.date(2023, 1, 19)),
            preserve_default=False,
        ),
    ]
