# Generated by Django 4.1.5 on 2023-01-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_rental_reserved_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='automatically_verifiable',
            field=models.BooleanField(blank=True, default=False, verbose_name='tells if someone is automatically verifiable, set to true if it fails'),
        ),
    ]
