# Generated by Django 4.1.5 on 2023-01-20 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0045_alter_profile_automatically_verifiable'),
    ]

    operations = [
        migrations.CreateModel(
            name='OauthVerificationProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=100)),
                ('device_code', models.CharField(max_length=100)),
                ('last_ping', models.DateTimeField()),
                ('target', models.TextField(verbose_name='id a provider')),
                ('access_token', models.CharField(blank=True, default=None, max_length=130, null=True)),
                ('access_token_exipiry', models.DateTimeField(blank=True, default=None, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=130, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
