# Generated by Django 4.1.5 on 2023-01-20 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_oauthverificationprocess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oauthverificationprocess',
            old_name='last_ping',
            new_name='verification_process_expires',
        ),
    ]
