# Generated by Django 4.1.5 on 2023-01-20 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_rename_last_ping_oauthverificationprocess_verification_process_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthverificationprocess',
            name='last_ping',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last time the server got pinged'),
        ),
        migrations.AddField(
            model_name='oauthverificationprocess',
            name='ping_interval',
            field=models.DurationField(default=datetime.timedelta(seconds=5)),
        ),
    ]
