# Generated by Django 4.1.5 on 2023-01-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_oauthverificationprocess_last_ping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthverificationprocess',
            name='faculty',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oauthverificationprocess',
            name='target',
            field=models.CharField(blank=True, max_length=100, verbose_name='id a provider'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='automatically_verifiable',
            field=models.BooleanField(blank=True, default=True, verbose_name='tells if someone is automatically verifiable, set to false if it fails'),
        ),
    ]
