# Generated by Django 4.1.5 on 2023-01-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_oauthverificationprocess_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='oauth_verified',
            field=models.BooleanField(default=False),
        ),
    ]
