# Generated by Django 4.1.5 on 2023-01-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_rename_oauth_verified_profile_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='canceled',
        ),
        migrations.AddField(
            model_name='reservation',
            name='canceled',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
