# Generated by Django 4.1.5 on 2023-01-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_remove_rental_canceled_reservation_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='description',
            field=models.TextField(default='', verbose_name='Description, why is this a suggestion for the other one?'),
        ),
    ]
