# Generated by Django 4.1.5 on 2023-01-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_suggestion_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='notified',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
