# Generated by Django 4.1.5 on 2023-01-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_reservation_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='notified',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
