# Generated by Django 4.1.5 on 2023-01-28 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_rental_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnPremiseWorkplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='onpremisebooking',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='onpremisebooking',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='onpremisebooking',
            name='slot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.onpremisetimeslot'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OnPremiseExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excludes', models.ManyToManyField(related_name='excluded_working_places', to='base.onpremiseworkplace')),
                ('working_place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='base.onpremiseworkplace')),
            ],
        ),
    ]
