# Generated by Django 4.1.5 on 2023-01-28 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_onpremiseworkplace_remove_onpremisebooking_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onpremiseworkplace',
            name='displayed',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='OnPremiseWorkplaceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('until_date', models.DateTimeField()),
                ('reason', models.TextField()),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.onpremiseworkplace')),
            ],
        ),
    ]
