# Generated by Django 4.1.5 on 2023-01-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_onpremiseworkplace_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='onpremiseworkplace',
            name='available',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
