# Generated by Django 4.1.5 on 2023-01-29 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_onpremiseworkplace_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onpremiseworkplace',
            old_name='available',
            new_name='amount',
        ),
    ]
