# Generated by Django 4.1.5 on 2023-01-29 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_rename_available_onpremiseworkplace_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onpremiseexclusion',
            old_name='working_place',
            new_name='workplace',
        ),
    ]
