# Generated by Django 4.1.5 on 2023-01-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_rename_working_place_onpremiseexclusion_workplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='onpremiseworkplace',
            name='exclusions',
            field=models.ManyToManyField(to='base.onpremiseworkplace'),
        ),
        migrations.DeleteModel(
            name='OnPremiseExclusion',
        ),
    ]
