# Generated by Django 4.1.5 on 2023-01-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_onpremiseworkplace_exclusions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onpremiseworkplace',
            name='exclusions',
            field=models.ManyToManyField(blank=True, to='base.onpremiseworkplace'),
        ),
    ]
