# Generated by Django 4.1.5 on 2023-01-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_alter_onpremiseworkplace_exclusions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onpremisetimeslot',
            name='day',
        ),
    ]
