# Generated by Django 4.1.5 on 2023-01-30 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_remove_onpremisetimeslot_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='onpremisetimeslot',
            name='day',
            field=models.DateField(default=datetime.date(2023, 1, 30)),
            preserve_default=False,
        ),
    ]
