# Generated by Django 4.1.5 on 2023-01-30 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_onpremisetimeslot_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onpremisebooking',
            name='slot',
        ),
        migrations.AddField(
            model_name='onpremisebooking',
            name='slot_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 5, 54, 37, 235177, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onpremisebooking',
            name='slot_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 5, 54, 44, 897265, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OnPremiseTimeSlot',
        ),
    ]
