# Generated by Django 4.1.5 on 2023-01-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_remove_onpremisebooking_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onpremisebooking',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
