# Generated by Django 4.1.5 on 2023-01-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_remove_onpremiseworkplace_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onpremisebooking',
            name='canceled',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
