# Generated by Django 4.1.5 on 2023-02-11 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_onpremisebooking_canceled'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.RemoveField(
            model_name='objecttypeinfo',
            name='object_type',
        ),
        migrations.RemoveConstraint(
            model_name='onpremisebooking',
            name='booking',
        ),
        migrations.DeleteModel(
            name='ObjectTypeInfo',
        ),
    ]
