# Generated by Django 4.2 on 2023-04-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_delete_notification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onpremiseworkplace',
            old_name='description',
            new_name='shortdescription',
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description, why is this a suggestion for the other one?'),
        ),
    ]
