# Generated by Django 4.2 on 2023-04-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_rename_description_onpremiseworkplace_shortdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onpremiseworkplace',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='onpremiseworkplace',
            name='shortdescription',
            field=models.TextField(default=''),
        ),
    ]
