# Generated by Django 4.2.1 on 2023-05-30 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 11, 38, 1, 421821, tzinfo=datetime.timezone.utc)),
        ),
    ]
