# Generated by Django 4.2.2 on 2023-07-07 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0076_alter_passwordreset_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_from', models.DateTimeField(default=None)),
                ('extended_until', models.DateTimeField(default=None)),
                ('extended_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('extended_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('extended_rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.rental')),
            ],
        ),
    ]
