# Generated by Django 4.2.3 on 2023-07-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='reserved_until',
        ),
    ]
