# Generated by Django 4.2.3 on 2023-07-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_remove_rental_reserved_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='extended_from',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='extension',
            name='extended_until',
            field=models.DateField(default=None),
        ),
    ]
