# Generated by Django 4.2.3 on 2023-07-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_alter_extension_extended_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='handed_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
